### PR TITLE
accessibility + responsiveness + design improvements

### LINKED ISSUE #3: Website improvements
I'm working on improving the overall website look and feel, and responsiveness.
Creating this issue to keep track of changes @kyleplo. Will work on branch `website-improvements`.

### PR DESCRIPTION
**Pull request by moeenio**
Fixes #3 

The site is nearly responsive (all except nav), I improved some look and feel, and the navs are accessible.

Use `ul` elements (wth li inside) in navs.

Preview : https://angry-booth-2e2d4b.netlify.com/

@kyleplo

### CODE REVIEW

**Comment by moeenio** [comment]
There is a bug on help and community server pages

**Comment by moeenio** [comment]
Should've fixed bugs, but not redeployed

**Comment by moeenio** [comment]
Deployed at link in first comment, and bugs fixed

**Comment by moeenio** [comment]
Added viewport meta tag for responsiveness, and description tag

**Comment by moeenio** [comment]
@kyleplo, also, shouldn't the download links point to overcast-electron instead of overcast ?

**Comment by kyleplo** [comment]
Looks good!

**Comment by moeenio** [comment]
> Looks good!

Could you merge it ? I said I didn't have write access, so I can't do it @kyleplo

**Pull request merged**
