### PR TITLE
Should work now (AFTER RESOLVING CONFLICTS CORRECTLY!!!!!!!!!)

### PR DESCRIPTION
**Pull request by moeenio**

### CODE REVIEW

**Comment by kyleplo** [comment]
Can you post a demo online? (last time i merged and then looked, i won't do that again)

**Comment by moeenio** [comment]
There! Preview at https://angry-booth-2e2d4b.netlify.com/ @kyleplo

**Comment by moeenio** [comment]
Last time I sent a comment saying I knew it glitched

**Comment by kyleplo** [comment]
> Last time I sent a comment saying I knew it glitched

I know now.

**Comment by kyleplo** [comment]
Looks good (I looked this time)

**Comment by kyleplo** [comment]
> Looks good (I looked this time)

Except the icons... @locness3

**Comment by moeenio** [comment]
What's wrong @kyleplo ?

**Comment by moeenio** [comment]
I guess we'll never know

**Comment by kyleplo** [comment]
Haha I don't even remember what the issue was and the preview link you sent seems to be dead. This was an interesting project...

**Comment by moeenio** [comment]
lmao, [the website is still up](https://overcastchat.github.io) though

**Pull request merged**
